import chalk from 'chalk';
import fs from 'fs/promises';
import path from 'path';
import { Pool } from 'pg';
import { apiClient, handleApiError } from '../lib/api.js';
import { getProjectConfig, getLocalEnv } from '../lib/config.js';
import { success, error, info, createSpinner } from '../lib/ui.js';

interface GenTypesOptions {
  output?: string;
}

export async function genTypes(options: GenTypesOptions) {
  console.log(chalk.bold.cyan('Generate TypeScript Types\n'));

  const config = await getProjectConfig();
  if (!config) {
    error('Not in a Kolaybase project. Run: kb init');
    process.exit(1);
  }

  const spinner = createSpinner('Generating types from database schema...');

  try {
    const env = await getLocalEnv();
    const pool = new Pool({
      connectionString: env.DATABASE_URL,
    });

    const client = await pool.connect();
    
    try {
      // Get all tables
      const { rows: tables } = await client.query(`
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public'
        ORDER BY table_name
      `);

      let typesContent = `// Generated by Kolaybase CLI
// Do not edit manually

export interface Database {
${tables.map((t: any) => `  ${t.table_name}: ${toPascalCase(t.table_name)};`).join('\n')}
}

`;

      // Generate types for each table
      for (const table of tables) {
        const { rows: columns } = await client.query(`
          SELECT 
            column_name, 
            data_type, 
            is_nullable,
            column_default
          FROM information_schema.columns
          WHERE table_name = $1
          ORDER BY ordinal_position
        `, [table.table_name]);

        const typeName = toPascalCase(table.table_name);
        
        typesContent += `export interface ${typeName} {\n`;
        
        columns.forEach((col: any) => {
          const tsType = pgTypeToTs(col.data_type);
          const optional = col.is_nullable === 'YES' || col.column_default ? '?' : '';
          typesContent += `  ${col.column_name}${optional}: ${tsType};\n`;
        });
        
        typesContent += `}\n\n`;
      }

      // Write to file
      const outputDir = options.output || 'types';
      await fs.mkdir(outputDir, { recursive: true });
      const outputPath = path.join(outputDir, 'database.ts');
      await fs.writeFile(outputPath, typesContent);

      spinner.succeed('Types generated successfully');
      success(`Written to ${chalk.cyan(outputPath)}`);
    } finally {
      client.release();
      await pool.end();
    }
  } catch (err) {
    spinner.fail('Failed to generate types');
    await handleApiError(err);
  }
}

interface GenClientOptions {
  lang?: string;
  output?: string;
}

export async function genClient(options: GenClientOptions) {
  console.log(chalk.bold.cyan('Generate API Client\n'));

  const config = await getProjectConfig();
  if (!config) {
    error('Not in a Kolaybase project. Run: kb init');
    process.exit(1);
  }

  const spinner = createSpinner('Generating API client...');

  try {
    const lang = options.lang || 'typescript';
    const outputDir = options.output || 'lib';

    if (lang === 'typescript') {
      await generateTsClient(config, outputDir);
    } else if (lang === 'javascript') {
      await generateJsClient(config, outputDir);
    } else if (lang === 'python') {
      await generatePyClient(config, outputDir);
    } else {
      throw new Error(`Unsupported language: ${lang}`);
    }

    spinner.succeed('Client generated successfully');
    success(`Written to ${chalk.cyan(outputDir)}`);
  } catch (err) {
    spinner.fail('Failed to generate client');
    await handleApiError(err);
  }
}

async function generateTsClient(config: any, outputDir: string) {
  const clientContent = `// Generated by Kolaybase CLI
import axios, { AxiosInstance } from 'axios';

export interface KolaybaseConfig {
  url?: string;
  anonKey?: string;
  serviceKey?: string;
}

export class KolaybaseClient {
  private client: AxiosInstance;
  private projectId: string;

  constructor(config: KolaybaseConfig = {}) {
    this.projectId = '${config.projectId}';
    
    this.client = axios.create({
      baseURL: config.url || process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': \`Bearer \${config.anonKey || process.env.ANON_KEY}\`,
      },
    });
  }

  // Execute raw SQL
  async sql<T = any>(query: string): Promise<T[]> {
    const { data } = await this.client.post('/sql/execute', {
      projectId: this.projectId,
      query,
    });
    return data.rows;
  }

  // Table operations
  table<T = any>(tableName: string) {
    return {
      select: async (columns = '*', options?: {
        where?: Record<string, any>;
        limit?: number;
        offset?: number;
        orderBy?: string;
      }): Promise<T[]> => {
        let query = \`SELECT \${columns} FROM \${tableName}\`;
        
        if (options?.where) {
          const conditions = Object.entries(options.where)
            .map(([k, v]) => \`\${k} = '\${v}'\`)
            .join(' AND ');
          query += \` WHERE \${conditions}\`;
        }
        
        if (options?.orderBy) {
          query += \` ORDER BY \${options.orderBy}\`;
        }
        
        if (options?.limit) {
          query += \` LIMIT \${options.limit}\`;
        }
        
        if (options?.offset) {
          query += \` OFFSET \${options.offset}\`;
        }

        return this.sql<T>(query);
      },

      insert: async (data: Partial<T> | Partial<T>[]): Promise<T[]> => {
        const rows = Array.isArray(data) ? data : [data];
        const keys = Object.keys(rows[0]);
        const values = rows.map(row => 
          \`(\${keys.map(k => \`'\${(row as any)[k]}'\`).join(', ')})\`
        ).join(', ');

        const query = \`
          INSERT INTO \${tableName} (\${keys.join(', ')}) 
          VALUES \${values}
          RETURNING *
        \`;

        return this.sql<T>(query);
      },

      update: async (data: Partial<T>, where: Record<string, any>): Promise<T[]> => {
        const sets = Object.entries(data)
          .map(([k, v]) => \`\${k} = '\${v}'\`)
          .join(', ');
        
        const conditions = Object.entries(where)
          .map(([k, v]) => \`\${k} = '\${v}'\`)
          .join(' AND ');

        const query = \`
          UPDATE \${tableName} 
          SET \${sets} 
          WHERE \${conditions}
          RETURNING *
        \`;

        return this.sql<T>(query);
      },

      delete: async (where: Record<string, any>): Promise<T[]> => {
        const conditions = Object.entries(where)
          .map(([k, v]) => \`\${k} = '\${v}'\`)
          .join(' AND ');

        const query = \`DELETE FROM \${tableName} WHERE \${conditions} RETURNING *\`;
        return this.sql<T>(query);
      },
    };
  }
}

export function createClient(config?: KolaybaseConfig): KolaybaseClient {
  return new KolaybaseClient(config);
}
`;

  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, 'kolaybase.ts'), clientContent);
}

async function generateJsClient(config: any, outputDir: string) {
  const clientContent = `// Generated by Kolaybase CLI
const axios = require('axios');

class KolaybaseClient {
  constructor(config = {}) {
    this.projectId = '${config.projectId}';
    
    this.client = axios.create({
      baseURL: config.url || process.env.API_URL || 'http://localhost:4000',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': \`Bearer \${config.anonKey || process.env.ANON_KEY}\`,
      },
    });
  }

  async sql(query) {
    const { data } = await this.client.post('/sql/execute', {
      projectId: this.projectId,
      query,
    });
    return data.rows;
  }

  table(tableName) {
    return {
      select: async (columns = '*', options = {}) => {
        let query = \`SELECT \${columns} FROM \${tableName}\`;
        
        if (options.where) {
          const conditions = Object.entries(options.where)
            .map(([k, v]) => \`\${k} = '\${v}'\`)
            .join(' AND ');
          query += \` WHERE \${conditions}\`;
        }

        return this.sql(query);
      },

      insert: async (data) => {
        const rows = Array.isArray(data) ? data : [data];
        const keys = Object.keys(rows[0]);
        const values = rows.map(row => 
          \`(\${keys.map(k => \`'\${row[k]}'\`).join(', ')})\`
        ).join(', ');

        const query = \`INSERT INTO \${tableName} (\${keys.join(', ')}) VALUES \${values} RETURNING *\`;
        return this.sql(query);
      },
    };
  }
}

function createClient(config) {
  return new KolaybaseClient(config);
}

module.exports = { KolaybaseClient, createClient };
`;

  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, 'kolaybase.js'), clientContent);
}

async function generatePyClient(config: any, outputDir: string) {
  const clientContent = `# Generated by Kolaybase CLI
import os
import requests
from typing import List, Dict, Any, Optional

class KolaybaseClient:
    def __init__(self, config: Optional[Dict[str, str]] = None):
        config = config or {}
        self.project_id = '${config.projectId}'
        self.base_url = config.get('url', os.getenv('API_URL', 'http://localhost:4000'))
        self.anon_key = config.get('anon_key', os.getenv('ANON_KEY'))
        
        self.session = requests.Session()
        self.session.headers.update({
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {self.anon_key}'
        })
    
    def sql(self, query: str) -> List[Dict[str, Any]]:
        response = self.session.post(
            f'{self.base_url}/sql/execute',
            json={'projectId': self.project_id, 'query': query}
        )
        response.raise_for_status()
        return response.json()['rows']
    
    def table(self, table_name: str):
        class TableOperations:
            def __init__(self, client, table):
                self.client = client
                self.table = table
            
            def select(self, columns='*', where=None, limit=None):
                query = f'SELECT {columns} FROM {self.table}'
                
                if where:
                    conditions = ' AND '.join([f"{k} = '{v}'" for k, v in where.items()])
                    query += f' WHERE {conditions}'
                
                if limit:
                    query += f' LIMIT {limit}'
                
                return self.client.sql(query)
        
        return TableOperations(self, table_name)

def create_client(config: Optional[Dict[str, str]] = None) -> KolaybaseClient:
    return KolaybaseClient(config)
`;

  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, 'kolaybase.py'), clientContent);
}

function toPascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function pgTypeToTs(pgType: string): string {
  const typeMap: Record<string, string> = {
    'integer': 'number',
    'bigint': 'number',
    'smallint': 'number',
    'decimal': 'number',
    'numeric': 'number',
    'real': 'number',
    'double precision': 'number',
    'serial': 'number',
    'bigserial': 'number',
    'character varying': 'string',
    'varchar': 'string',
    'character': 'string',
    'char': 'string',
    'text': 'string',
    'boolean': 'boolean',
    'date': 'string',
    'timestamp': 'string',
    'timestamp without time zone': 'string',
    'timestamp with time zone': 'string',
    'time': 'string',
    'json': 'any',
    'jsonb': 'any',
    'uuid': 'string',
    'bytea': 'Buffer',
  };

  return typeMap[pgType.toLowerCase()] || 'any';
}
