import Conf from 'conf';
import path from 'path';
import fs from 'fs/promises';

export interface UserConfig {
  apiUrl?: string;
  accessToken?: string;
  refreshToken?: string;
  userId?: string;
  username?: string;
  email?: string;
}

export interface ProjectConfig {
  projectId?: string;
  projectName?: string;
  projectSlug?: string;
  teamId?: string;
  linkedAt?: string;
}

const userConfig = new Conf<UserConfig>({
  projectName: 'kolaybase',
  configName: 'config',
});

// Get current project directory
export async function getProjectRoot(): Promise<string | null> {
  let currentDir = process.cwd();
  
  while (currentDir !== path.parse(currentDir).root) {
    const configPath = path.join(currentDir, '.kolaybase');
    try {
      await fs.access(configPath);
      return currentDir;
    } catch {
      currentDir = path.dirname(currentDir);
    }
  }
  
  return null;
}

// Project-specific configuration
export async function getProjectConfig(): Promise<ProjectConfig | null> {
  const projectRoot = await getProjectRoot();
  if (!projectRoot) return null;

  const configPath = path.join(projectRoot, '.kolaybase', 'config.json');
  
  try {
    const data = await fs.readFile(configPath, 'utf-8');
    return JSON.parse(data);
  } catch {
    return null;
  }
}

export async function setProjectConfig(config: ProjectConfig): Promise<void> {
  const projectRoot = process.cwd();
  const configDir = path.join(projectRoot, '.kolaybase');
  const configPath = path.join(configDir, 'config.json');

  await fs.mkdir(configDir, { recursive: true });
  await fs.writeFile(configPath, JSON.stringify(config, null, 2));
}

// User configuration helpers
export function getUserConfig(): UserConfig {
  return userConfig.store;
}

export function setUserConfig(config: Partial<UserConfig>): void {
  userConfig.set(config);
}

export function clearUserConfig(): void {
  userConfig.clear();
}

export function getApiUrl(): string {
  return userConfig.get('apiUrl') || 'http://localhost:4000';
}

export function getAccessToken(): string | undefined {
  return userConfig.get('accessToken');
}

export function setAccessToken(token: string): void {
  userConfig.set('accessToken', token);
}

export function getRefreshToken(): string | undefined {
  return userConfig.get('refreshToken');
}

export function setRefreshToken(token: string): void {
  userConfig.set('refreshToken', token);
}

export function isLoggedIn(): boolean {
  return !!userConfig.get('accessToken');
}

export function setApiUrl(url: string): void {
  userConfig.set('apiUrl', url);
}

// Write a .env file with all project credentials
export async function writeEnvFile(project: any): Promise<void> {
  const lines = [
    '# Kolaybase — generated by "kb init" / "kb link"',
    '',
    `PROJECT_ID=${project.id}`,
    `PROJECT_SLUG=${project.slug}`,
    '',
    `DB_HOST=${project.dbHost}`,
    `DB_PORT=${project.dbPort}`,
    `DB_NAME=${project.dbName}`,
    `DB_USER=${project.dbUser}`,
    `DB_PASSWORD=${project.dbPassword}`,
    `DATABASE_URL=postgresql://${project.dbUser}:${project.dbPassword}@${project.dbHost}:${project.dbPort}/${project.dbName}`,
    '',
    `KEYCLOAK_REALM=${project.keycloakRealm}`,
    `ANON_KEY=${project.anonKey}`,
    `SERVICE_KEY=${project.serviceKey}`,
    '',
  ];

  await fs.writeFile('.env', lines.join('\n'));

  // Make sure .gitignore has .env
  try {
    let gi = '';
    try { gi = await fs.readFile('.gitignore', 'utf-8'); } catch { /* noop */ }
    if (!gi.includes('.env')) {
      await fs.writeFile('.gitignore', gi + '\n.env\n');
    }
  } catch { /* best-effort */ }
}

// Local .env management
export async function getLocalEnv(): Promise<Record<string, string>> {
  const projectRoot = await getProjectRoot();
  if (!projectRoot) return {};

  const envPath = path.join(projectRoot, '.env');
  
  try {
    const content = await fs.readFile(envPath, 'utf-8');
    const env: Record<string, string> = {};
    
    content.split('\n').forEach(line => {
      line = line.trim();
      if (!line || line.startsWith('#')) return;
      
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        env[key.trim()] = valueParts.join('=').trim();
      }
    });
    
    return env;
  } catch {
    return {};
  }
}

export async function setLocalEnv(key: string, value: string): Promise<void> {
  const projectRoot = await getProjectRoot();
  if (!projectRoot) {
    throw new Error('Not in a Kolaybase project directory');
  }

  const envPath = path.join(projectRoot, '.env');
  let content = '';
  
  try {
    content = await fs.readFile(envPath, 'utf-8');
  } catch {
    // File doesn't exist, will create new
  }

  const lines = content.split('\n');
  let found = false;
  
  const newLines = lines.map(line => {
    const trimmed = line.trim();
    if (trimmed.startsWith(`${key}=`)) {
      found = true;
      return `${key}=${value}`;
    }
    return line;
  });

  if (!found) {
    newLines.push(`${key}=${value}`);
  }

  await fs.writeFile(envPath, newLines.join('\n'));
}

export async function unsetLocalEnv(key: string): Promise<void> {
  const projectRoot = await getProjectRoot();
  if (!projectRoot) {
    throw new Error('Not in a Kolaybase project directory');
  }

  const envPath = path.join(projectRoot, '.env');
  
  try {
    const content = await fs.readFile(envPath, 'utf-8');
    const lines = content.split('\n').filter(line => {
      const trimmed = line.trim();
      return !trimmed.startsWith(`${key}=`);
    });
    
    await fs.writeFile(envPath, lines.join('\n'));
  } catch {
    // File doesn't exist, nothing to do
  }
}
