-- Phase 0: migration_runs table
-- Stores planned and applied tenant-database migration runs generated by
-- MigrationsService. Linked to projects via projectId (CASCADE delete).

CREATE TABLE "migration_runs" (
    "id"                     TEXT NOT NULL,
    "project_id"             TEXT NOT NULL,
    "from_blueprint_version" INTEGER NOT NULL,
    "to_blueprint_version"   INTEGER NOT NULL,
    "status"                 VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    "plan_json"              JSONB NOT NULL,
    "sql_statements"         JSONB NOT NULL DEFAULT '[]',
    "applied_statements"     INTEGER NOT NULL DEFAULT 0,
    "error_message"          VARCHAR(2000),
    "started_at"             TIMESTAMPTZ,
    "completed_at"           TIMESTAMPTZ,
    "created_at"             TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "migration_runs_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "migration_runs_project_id_fkey"
        FOREIGN KEY ("project_id") REFERENCES "projects"("id")
        ON DELETE CASCADE
);

CREATE INDEX "migration_runs_project_id_idx"
    ON "migration_runs"("project_id");

CREATE INDEX "migration_runs_project_id_status_idx"
    ON "migration_runs"("project_id", "status");
