ALTER TABLE "project_auth_configs"
  ADD COLUMN IF NOT EXISTS "microsoft_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "microsoft_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "microsoft_client_secret" TEXT,
  ADD COLUMN IF NOT EXISTS "apple_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "apple_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "apple_client_secret" TEXT,
  ADD COLUMN IF NOT EXISTS "gitlab_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "gitlab_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "gitlab_client_secret" TEXT,
  ADD COLUMN IF NOT EXISTS "linkedin_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "linkedin_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "linkedin_client_secret" TEXT,
  ADD COLUMN IF NOT EXISTS "facebook_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "facebook_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "facebook_client_secret" TEXT,
  ADD COLUMN IF NOT EXISTS "twitter_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "twitter_client_id" TEXT,
  ADD COLUMN IF NOT EXISTS "twitter_client_secret" TEXT;
